server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/limjongwoo/git-local-repo
          uri: https://github.com/jongwoolim/spring-cloud-config
#        uesrname: [your username] private일 경우
#        password: [your password] private일 경우